import Head from "next/head";
import Header from "../components/Header";
import Resume from "../components/Resume";
import Footer from "../components/Footer";

export default function Home() {
  const variants = {
    hidden: { opacity: 0 },
    visible: { opacity: 1 },
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col h-screen">
        <Header />
        <Resume />
        <div className="flex-grow"></div>
        <Footer />
      </div>
    </div>
  );
}
